SELECT ENBRRH.EQUIPID AS EMS_ID,
       ENBRRH.EQUIPID AS EMS_NAME,
       ENBRRH.DUID AS DU_ID,
       ENBRRH.DUID AS DU_NAME,
       ENBRRH.RUID AS RU_ID,
       ENBRRH.RUID AS RU_NAME,
       RRH.CELLNUM AS CELL_NUM,
       RRH.CELL_ID_DEC AS CELL_ID,
       RRH.CELLFDDID AS RU_PARAM
FROM CMUSER.TBD_CM_APP_LSMRRHCONF RRH,
     CMUSER.TBD_CM_APP_LSMENBRRHCONF ENBRRH
WHERE RRH.CELLFDDID IS NOT NULL
  AND RRH.DU = ENBRRH.DUID
  AND RRH.RU = ENBRRH.RUID
  AND RRH.CELLNUM = ENBRRH.CELLNUM