SELECT CONF.EMS_ID AS EMS_ID,
       CONF.EMS_NAME AS EMS_NAME,
       CONF.DU_ID AS DU_ID,
       CONF.DU_NAME AS DU_NAME,
       CONF.RU_ID AS RU_ID,
       CONF.RU_NAME AS RU_NAME,
       RRH.CELL_ID_DEC AS CELL_ID,
       RRH.CELLNUM AS CELL_NUM ,
       FDD_ID AS RU_PARAM
FROM CMUSER.TBF_CM_APP_ELGDURU_CONF CONF,CMUSER.TBF_CM_APP_RRHCONF RRH
WHERE  CONF.RU_ID = RRH.RU