SELECT DISTINCT A.EQUIPID AS EMS_ID,
                A.EQUIPID AS EMS_NAME,
                DU.CURRENTEQUIPID AS DU_ID,
                DU.CURRENTEQUIPID AS DU_NAME,
                RU.CURRENTEQUIPID AS RU_ID,
                RU.CURRENTEQUIPID AS RU_NAME,
                RRH.CELLNUM AS CELL_NUM,
                B.CELLIDENTITY AS CELL_ID,
                A.ENBID||'/'||B.CELLFDDID AS RU_PARAM
FROM OSSCM.CM_INF_LSMCELL_NSN_RMOD@LK_OSSMASTER A,
     OSSCM.CM_INF_LSMCELL_NSN@LK_OSSMASTER B,
     CMUSER.TBD_CM_APP_LSMENBRRHCONF RRH,
     (SELECT * FROM  OSSMASTER.OSS_EQUIPMAST@LK_OSSMASTER WHERE EQUIPTYPECODE = 'LTED' AND VENDORCODE = 'NSNN') DU,
     (SELECT * FROM  OSSMASTER.OSS_EQUIPMAST@LK_OSSMASTER WHERE EQUIPTYPECODE = 'LTER' AND VENDORCODE = 'NSNN') RU
WHERE A.RU_ID = B.RRHNAME
  AND A.RU_ID = RU.CURRENTEQUIPID
  AND RU.PARENTEQUIPID = DU.EQUIPID
  AND B.RRHNAME = RRH.RUID
  AND B.CELLFDDID = RRH.CELLNUM
UNION ALL
SELECT DISTINCT A.EQUIPID AS EMS_ID,
                A.EQUIPID AS EMS_NAME,
                DU.CURRENTEQUIPID AS DU_ID,
                DU.CURRENTEQUIPID AS DU_NAME,
                RU.CURRENTEQUIPID AS RU_ID,
                RU.CURRENTEQUIPID AS RU_NAME,
                RRH.CELLNUM AS CELL_NUM,
                B.CELLIDENTITY AS CELL_ID,
                A.ENBID||'/'||A.RMOD AS RU_PARAM
FROM OSSCM.CM_INF_LSMCELL_NSN_RMOD@LK_OSSMASTER A,
     OSSCM.CM_INF_LSMCELL_NSN@LK_OSSMASTER B,
     CMUSER.TBD_CM_APP_LSMENBRRHCONF RRH,
     (SELECT * FROM  OSSMASTER.OSS_EQUIPMAST@LK_OSSMASTER WHERE EQUIPTYPECODE = 'LTED' AND VENDORCODE = 'NSNN') DU,
     (SELECT * FROM  OSSMASTER.OSS_EQUIPMAST@LK_OSSMASTER WHERE EQUIPTYPECODE = 'LTER' AND VENDORCODE = 'NSNN') RU
WHERE A.RU_ID = B.RRHNAME
  AND A.RU_ID = RU.CURRENTEQUIPID
  AND RU.PARENTEQUIPID = DU.EQUIPID
  AND B.RRHNAME = RRH.RUID
  AND B.CELLFDDID = RRH.CELLNUM ;