SELECT CONF.EMS_ID AS EMS_ID,
       CONF.EMS_NAME AS EMS_NAME,
       CONF.DU_ID AS DU_ID,
       CONF.DU_NAME,
       CONF.RU_ID AS RU_ID,
       CONF.RU_NAME,
       CELL.CELL_ID_DEC AS CELL_ID,
       CELL.CELLNUM AS CELL_NUM,
       CONF.MRBTS || '/' || RMOD.RMOD AS RU_PARAM
FROM   CMUSER.TBF_CM_APP_NSNDURU_CONF CONF,
       CMUSER.TBD_CM_INFO_NSNCELL_RMOD RMOD,
       CMUSER.TBF_CM_APP_RRHCONF CELL
WHERE  CONF.RU_ID = RMOD.RU_ID and CONF.RU_ID = CELL.RU
UNION ALL
SELECT CONF.EMS_ID AS EMS_ID,
       CONF.EMS_NAME AS EMS_NAME,
       CONF.DU_ID AS DU_ID,
       CONF.DU_NAME,
       CONF.RU_ID AS RU_ID,
       CONF.RU_NAME,
       CELL.CELL_ID_DEC AS CELL_ID,
       CELL.CELLNUM AS CELL_NUM,
       CONF.MRBTS || '/' || CONF.CELLFDD AS RU_PARAM
FROM   CMUSER.TBF_CM_APP_NSNDURU_CONF CONF,
       CMUSER.TBD_CM_INFO_NSNCELL_RMOD RMOD,
       CMUSER.TBF_CM_APP_RRHCONF CELL
WHERE  CONF.RU_ID = RMOD.RU_ID and CONF.RU_ID = CELL.RU;