SELECT RRH.EQUIPID AS EMS_ID,
       RRH.EQUIPID AS EMS_NAME,
       DUID AS DU_ID,
       DUID AS DU_NAME,
       RUID AS RU_ID,
       RUID AS RU_NAME,
       RRH.CELLNUM AS CELL_NUM,
       LSMRRH.CELL_ID_DEC as CELL_ID,
       DUID || '/UMP00/BID' || CONNECT_BDID || '/RuPort' || CONNECT_PORTID || '/Cascade' || CASCADE_RRHID AS RU_PARAM
FROM CMUSER.TBD_CM_APP_LSMENBRRHCONF RRH,
     CMUSER.TBD_CM_APP_LSMRRHCONF LSMRRH,
     CMUSER.TBD_CM_BASE_RU_SITEINFO SITE
WHERE RRH.EQUIPID LIKE '%LSM%'
  AND RRH.RUID = LSMRRH.RU
  AND RRH.CELLNUM = LSMRRH.CELLNUM
  AND SITE.GUBUN = 'Master'
  AND RRH.RUID = SITE.CURRENT_EQUIP_ID
  AND RRH.CELLNUM = SITE.CELL_NUM
union all
SELECT RRH.EQUIPID AS EMS_ID,
       RRH.EQUIPID AS EMS_NAME,
       DUID AS DU_ID,
       DUID AS DU_NAME,
       RUID AS RU_ID,
       RUID AS RU_NAME,
       RRH.CELLNUM AS CELL_NUM,
       LSMRRH.CELL_ID_DEC as CELL_ID,
       DUID || '/UMP00/cNum'||rrh.cellnum AS RU_PARAM
FROM CMUSER.TBD_CM_APP_LSMENBRRHCONF RRH,
     CMUSER.TBD_CM_APP_LSMRRHCONF LSMRRH,
     CMUSER.TBD_CM_BASE_RU_SITEINFO SITE
WHERE RRH.EQUIPID LIKE '%LSM%'
  AND RRH.RUID = LSMRRH.RU
  AND RRH.CELLNUM = LSMRRH.CELLNUM
  AND SITE.GUBUN = 'Master'
  AND RRH.RUID = SITE.CURRENT_EQUIP_ID
  AND RRH.CELLNUM = SITE.CELL_NUM